FROM node:20-bookworm-slim
RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

# Gera o client do Prisma (necessário!)
RUN npx prisma generate

# (opcional) aplica apenas prod deps
RUN npm prune --production

ENV NODE_ENV=production
ENV PORT=3001
ENV UPLOAD_PATH=/app/uploads
RUN mkdir -p ${UPLOAD_PATH} && chmod -R 755 ${UPLOAD_PATH}

EXPOSE 3001
CMD ["node", "server.js"]